Enable intermodule dependencies
ingzkp/zinc pull request #6
Opened 2021-02-27 20:45 UTC by mvdbos

This enables modules depending on other modules by topologically sorting source files based on their `mod` statements before starting compilation. This works, as long as there are no cyclic dependencies. If there are, compilation fails.

This PR badly needs review on efficiency and style by a Rustacean, since I lack knowledge of idiomatic constructs. Therefore very inelegant.

2021-03-01 16:35 UTC, alexeykoren reviewed
Looks fine to me if it works. I'm not a Rustafarian and for me it looks ugly - so it should be perfect from Rust style perspective.

2021-03-01 16:55 UTC, vnermolaev requested changes

2021-03-01 16:55 UTC, vnermolaev commented on zinc-compiler/src/file/mod.rs
> +        let mut modules = Vec::<String>::new();
IMO a nicer way is 
```rust
Ok(syntax_tree.statements
        .into_iter()
        .fold(Vec::new(), |mut modules, statement| {
            if let Statement::Mod(s) = statement {
                modules.push(s);
            }
            modules
         })
 );
```

2021-03-01 16:55 UTC, vnermolaev commented on zinc-compiler/src/file/mod.rs
> +        let next_file_id = INDEX.read().expect(crate::PANIC_MUTEX_SYNC).len();
Notice that you return the `Result` type, but you have a lot of `expect`s. That feels more of the throw-exception style :).
you can have `let next_file_id = INDEX.read()?.len();`

2021-03-01 16:55 UTC, vnermolaev commented on zinc-compiler/src/main.rs
> +    for m in found_modules.into_iter() {
I think you are looking for this 
https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.try_for_each

2021-03-01 16:55 UTC, vnermolaev commented on zinc-compiler/src/main.rs
> +    for file in ordered_source_files.clone().into_iter() {
Do it with `for_each`
an imperative way would be `for file in &ordered_...` or `for file in ordered_...iter()`, this way you don't consume the vector and no cloning is needed.

2021-03-01 16:55 UTC, vnermolaev commented on zinc-compiler/src/main.rs
> +            .expect("Compilation failed during module graph ordering");
Perhaps return it as a result? to me, an appropriate place to fail would be in `main_inner`.

2021-03-01 16:55 UTC, vnermolaev commented on zinc-compiler/src/main.rs
> +        .map_err(|e: Error| -> Error {
Not sure whether you actually need to spell out all the types.

2021-03-01 16:55 UTC, vnermolaev commented on zinc-compiler/src/main.rs
> +    for source_file_path in ordered_source_files.into_iter() {
I do prefer a more functional style, but it was already this way in the source... :(

2021-03-01 17:52 UTC, mvdbos commented on zinc-compiler/src/file/mod.rs
> +        let mut modules = Vec::<String>::new();
Nice!

2021-03-01 17:59 UTC, mvdbos commented on zinc-compiler/src/file/mod.rs
> +        let next_file_id = INDEX.read().expect(crate::PANIC_MUTEX_SYNC).len();
I know, this is also copy-pasted from the function above, so not changing this one. 🤷

2021-03-01 18:04 UTC, mvdbos commented on zinc-compiler/src/main.rs
> +    for file in ordered_source_files.clone().into_iter() {
Done. Thanks.

2021-03-01 18:28 UTC, mvdbos commented on zinc-compiler/src/main.rs
> +            .expect("Compilation failed during module graph ordering");
The reason to do this, is to break out of the recursion immediately here. I agree it is not elegant AT ALL, but otherwise will have to make more changes to the depth-first algo so that cyclic dependency detection still works as expected.

2021-03-01 18:54 UTC, mvdbos commented on zinc-compiler/src/main.rs
> +    for m in found_modules.into_iter() {
Nicer, but still requires the expect after it, to jump out of the recursion as mentioned elsewhere.

2021-03-01 18:56 UTC, mvdbos commented on zinc-compiler/src/main.rs
> +        .map_err(|e: Error| -> Error {
Not sure either :-).
Removed.

2021-03-01 18:56 UTC, mvdbos commented on zinc-compiler/src/main.rs
> +    for source_file_path in ordered_source_files.into_iter() {
Yep.

2021-03-01 18:58 UTC, mvdbos commented
So, I know I could  get rid of the `expect`s with some refactoring of the recursion, but given that this nasty construct is already used elsewhere to fail compilation, I propose we leave it in as is. Meaning that I propose to make no further changes to this for now.

2021-03-02 08:11 UTC, vnermolaev approved these changes

2021-03-02 08:11 UTC, vnermolaev commented on zinc-compiler/src/main.rs
> +    // temp_marks.insert(n.clone(), true);
Should this be removed?

2021-03-02 08:15 UTC, mvdbos commented on zinc-compiler/src/main.rs
> +    // temp_marks.insert(n.clone(), true);
Yep, done.

2021-03-02 08:16 UTC, merged

2021-03-02 08:22 UTC, vnermolaev commented
> Looks fine to me if it works. I'm not a Rustafarian and for me it looks ugly - so it should be perfect from Rust style perspective.

You are walking a fine line between hatred and homage :)